repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files

    - repo: https://gitlab.com/jvenom/elixir-pre-commit-hooks
      rev: v1.2.0
      hooks:
          - id: mix-format

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "50c5478ed9e10bf360335449280cf2a67f4edb7a"
      hooks:
          - id: prettier
