name: Backend Tests

on:
    pull_request:
        branches: [main]

jobs:
    backend-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: |
                      target
                      ~/.cargo/registry
                      ~/.cargo/git
                  key: cargo-${{ hashFiles('**/Cargo.lock') }}
            - run: cargo test --manifest-path back/Cargo.toml
