name: Backend Tests

on:
    pull_request:
        branches: [main]

jobs:
    backend-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: rustup toolchain install stable --component llvm-tools-preview
            - name: Install cargo-llvm-cov
              uses: taiki-e/install-action@cargo-llvm-cov
            - uses: actions/cache@v3
              with:
                  path: |
                      target
                      ~/.cargo/registry
                      ~/.cargo/git
                  key: cargo-${{ hashFiles('**/Cargo.lock') }}
            - run: cargo llvm-cov --manifest-path back/Cargo.toml
