name: Build

on:
    workflow_run:
        workflows: [Check]
        types: [completed]
        branches: [main]

env:
    REGISTRY: ghcr.io

jobs:
    build:
        name: "Build Docker containers"
        runs-on: "ubuntu-latest"
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Determine the short hash of the current commit
              run: echo "SHORT_HASH=$(git rev-parse --short HEAD)" >>${GITHUB_ENV}

            - name: Create the name of the frontend image
              run: echo "FRONT_IMAGE_NAME=${REGISTRY}/${GITHUB_REPOSITORY,,}-front" >>${GITHUB_ENV}

            - name: Create the name of the backend image
              run: echo "BACK_IMAGE_NAME=${REGISTRY}/${GITHUB_REPOSITORY,,}-back" >>${GITHUB_ENV}

            - name: Log in to the GitHub Container registry
              uses: docker/login-action@d398f07826957cd0a18ea1b059cf1207835e60bc
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build the front Docker image
              run: docker image build --tag '${{ env.FRONT_IMAGE_NAME }}:latest' --tag '${{ env.FRONT_IMAGE_NAME }}:${{ env.SHORT_HASH }}' ./front

            - name: Build the back Docker image
              run: docker image build --tag '${{ env.BACK_IMAGE_NAME }}:latest' --tag '${{ env.BACK_IMAGE_NAME }}:${{ env.SHORT_HASH }}' ./back

            - name: Push the front Docker image
              run: docker image push --all-tags '${{ env.FRONT_IMAGE_NAME }}'

            - name: Push the back Docker image
              run: docker image push --all-tags '${{ env.BACK_IMAGE_NAME }}'
