name: Check

on:
    workflow_dispatch:
    workflow_call:
    pull_request:
        branches: [main]

jobs:
    check-pre-commit:
        name: "Check pre-commit"
        runs-on: "ubuntu-latest"

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup beam
              uses: erlef/setup-beam@v1
              with:
                  otp-version: 25
                  elixir-version: 1.14.4

            - name: Set up Python
              uses: actions/setup-python@v3

            - name: Install pre-commit
              run: pip install pre-commit

            - name: Cache pre-commit
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pre-commit
                  key: precommit-${{ hashFiles('.pre-commit-config.yaml') }}

            - name: Run pre-commit
              run: pre-commit run --all

    unit:
        name: "Unit tests (OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}})"
        runs-on: "ubuntu-20.04"
        strategy:
            matrix:
                otp: ["23", "24", "25"]
                elixir: ["1.14.4"]
        steps:
            - uses: actions/checkout@v3
            - uses: erlef/setup-beam@v1
              with:
                  otp-version: ${{matrix.otp}}
                  elixir-version: ${{matrix.elixir}}
            - run: cd backend && mix deps.get
            - run: cd backend && mix test
