name: Check pre-commit

on:
    pull_request:
        branches: [main]

jobs:
    check-pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - run: pip install pre-commit
            - name: Cache pre-commit
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pre-commit
                  key: precommit-${{ hashFiles('.pre-commit-config.yaml') }}
            - run: pre-commit run --all
