name: Deploy

on:
    workflow_run:
        workflows: [Build]
        types: [completed]
        branches: [main]

jobs:
    deploy-production:
        name: "Deploy to production"
        runs-on: "ubuntu-latest"
        environment: production

        permissions:
            packages: read

        steps:
            - name: Invoke deployment hook
              uses: distributhor/workflow-webhook@v2
              env:
                  webhook_url: ${{ secrets.WEBHOOK_URL }}
                  webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
